### ISSUE TITLE
External InfluxDB / Grafana

### ISSUE THREAD

**Issue by n1nj4888** [frdmn/docker-speedtest-grafana#10]
Hi,

For those of us with existing InfluxDB and Grafana containers/services, Is it possible to run the Speedtest Docker image without creating new InfluxDB and grafana containers? 

Looking at your docker-compose.yml it looks to create 3 separate containers for Speedtest, influx and grafana so can I assume that by only using “frdmn/speedtest-grafana“, the Speedtest would run on its own and if so, how to specify an existing external InfluxDB host/port/username/password/database to write to?

Thanks!

**Comment by frdmn** [comment]
Hi @n1nj4888, that should be possible by setting [the `INFLUXDB_DB` and `INFLUXDB_HOST` environment variables](https://github.com/frdmn/docker-speedtest-grafana/blob/master/docker/speedtest/Dockerfile#L21-L22) and rebuilding the container afterwards. At the moment it doesn't check user/password authentication:

https://github.com/frdmn/docker-speedtest-grafana/blob/master/docker/speedtest/index.js#L37-L40

**Comment by frdmn** [comment]
Added in latest version :)

**Comment by n1nj4888** [comment]
Awesome! Thanks for this!
