### ISSUE TITLE
[Feature Request] - Multiple Speedtest Servers

### ISSUE THREAD

**Issue by RickBankers** [frdmn/docker-speedtest-grafana#19]
It would be nice if we could have a list of speedtest serverids that it would loop through rather than just relying on a single speedtest server for every test. I think a maximum of 3 would be great and having it move to the next serverid in the list each time it performs the test would give a better overall result than just hitting the same server every time.

**Comment by frdmn** [comment]
Looks like this is a duplicate of #12. Thanks for reporting though!
