### ISSUE TITLE
Provide a docker image on hub.docker.com

### ISSUE THREAD

**Issue by D3473R** [frdmn/docker-speedtest-grafana#6]
It would be awesome if you could provide a docker image on hub.docker.com.
For deployment it will then be no longer necessary to clone and build the project ourselfes.
The docs how to setup an automated build are here: https://docs.docker.com/docker-hub/builds/
If you have any questions, hit me up.

Regards,
D3473R

**Comment by frdmn** [comment]
Thanks for the suggestion! Just pushed it to Docker Hub: 

https://hub.docker.com/r/frdmn/speedtest-grafana
