### ISSUE TITLE
Feature request: Give option to select specific Speedtest server

### ISSUE THREAD

**Issue by anuragbhatia** [frdmn/docker-speedtest-grafana#9]
Please consider giving option via envionment variable to run again specific target. One can pass speedtest server ID and then server tests against that. 

Example of test against specific server: 

```
docker run --rm moutten/speedtest-cli --list | grep Airtel | grep Mumbai
 2827) Bharti Airtel Ltd (Mumbai, India) [13.76 km]
19081) Airtel Broadband (Mumbai, India) [13.76 km]
```

This shows ID of the server - 2827 and 19081.

**Comment by frdmn** [comment]
Just added, can you give it a try?

**Comment by anuragbhatia** [comment]
Pulled the latest code and updated .env file and left it to check later. Now I see no change. Seems like docker-compose.yml wasn't updated to take the speedteest_server variable. 

I just made a pull request with that update. 
Thanks.
